version: '3.2'

networks:
  cvs:
    external: true

volumes:
  pgdata_cvs: {}

services:

  python:
    image: cvs/python
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: cvs-python

  janus:
    image: cvs/janus
    build:
      context: docker/janus
      args:
        - PUBLIC_IP
    container_name: cvs-janus
    networks:
      - cvs
    restart: always
    ports:
    - 10000-10200:10000-10200/udp

  postgres:
    image: cvs/postgres
    build:
      context: docker/postgres
      args:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    container_name: cvs-postgres
    networks:
      - cvs
    restart: always
    volumes:
      - pgdata_cvs:/var/lib/postgresql/data

  server:
    image: cvs/server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
      args:
        - JANUS_URL=ws://janus:8188/janus-ws
        - SERVER_PORT=80
        - SDK_API_URI=/cvs/api
        - SDK_SIGNAL_URI=/cvs/ws
        - POSTGRES_DSN
    container_name: cvs-server
    command: python -m cvs.server
    networks:
      - cvs
    depends_on:
      - postgres
#      - janus
    restart: always
