"""empty message

Revision ID: ebf88e22d694
Revises: c1550f3b60d0
Create Date: 2020-10-26 14:51:18.732554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebf88e22d694'
down_revision = 'c1550f3b60d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('jwt_secret', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('session', sa.Column('app_id', sa.String(), nullable=False))
    op.alter_column('session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'session', 'application', ['app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.alter_column('session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('session', 'app_id')
    op.drop_table('application')
    # ### end Alembic commands ###
